### ISSUE TITLE
benchmark.fyi link in README.md is pointing to a ArcGIS instance

### ISSUE THREAD

**Issue by janniswidderich** [evanphx/benchmark-ips#108]
The link to benchmark.fyi in the README.md in the section [Online sharing](https://github.com/evanphx/benchmark-ips#online-sharing) is pointing to what looks like a default page for ArcGIS, which I guess is not where that should be pointing. A quick google shows that https://ips.fastruby.io/ is probably where that link should be pointing.

**Comment by nateberkopec** [comment]
@etagwerker Are you/Ombu interested in a PR here that:

1. Changes the domain of the 'benchmark FYI we're trying to POST to' via an env variable? 
2. Changes the default to your domain?

**Comment by nateberkopec** [comment]
Basically I'm fine with just changing the default here to whoever is currently running an FYI instance that I personally trust (I know Ernesto/fastruby.io IRL). I understand there will be some churn in hosting a free service for everyone else over the years.

**Comment by etagwerker** [comment]
@nateberkopec Hey, yes, we are definitely interested in that. I can submit a PR later today. https://ips.fastruby.io is running the FastRuby.io fork: https://github.com/fastruby/benchmark.fyi 

@janniswidderich Could you please test that sharing works using the SHARE_URL environment variable? When you run your benchmark, you have to include this snippet right before running your command: 

```
SHARE_URL=https://ips.fastruby.io ./bin/run-your-benchmark.sh
```

**Comment by nateberkopec** [comment]
Oh nice, I thought that env var already existed but I went looking for a commit from you, I didn't know Evan built that into the original design

**Comment by janniswidderich** [comment]
@etagwerker That is printing a working URL as expected 👍 

(off topic: I have a question about running benchmarks with this gem, what would be a good place to ask that? is there a discord or something where knowledgeable people hang around?)

**Comment by nateberkopec** [comment]
this issue tracker is slow and we don't have a separate channel, so it's OK to ask on here.

**Comment by kbrock** [comment]
Has anyone had success storing metrics in benchmark.fyi? Or locally hosted?

I ended up just storing locally in a file (via benchmark-sweet) but using a service with a few graphs is very appealing.

**Comment by etagwerker** [comment]
@kbrock I'm very interested in that idea and that is part of the roadmap for this fork: https://github.com/fastruby/benchmark.fyi -- I should probably document the roadmap in a set of issues for that project. 

Right now benchmark.fyi does not support that because there is no way to connect one report to another report. I've added an issue to add more attributes per report. You can find it over here: https://github.com/fastruby/benchmark.fyi/issues/1
