### ISSUE TITLE
Suite Only Availabe via config

### ISSUE THREAD

**Issue by allcentury** [evanphx/benchmark-ips#112]
This isn't possible today:

```ruby
Benchmark.ips do |x|
  x.suite = suite
  x.warmup = 3
  x.time = 10
  x.iterations = 5
end
```

but this is

```ruby
Benchmark.ips do |x|
  x.config(
    suite: suite,
    warmup: 3,
    time: 10,
    iterations: 5,
  )
```

Is not being able to set `x.suite = ` a miss?  If so, I'm happy to PR that change.

**Comment by nateberkopec** [comment]
I think this would be a fine addition! Good catch.

**Comment by kbrock** [comment]
I really don't like introducing more to the object's api.
BUT, i had thought this was already in there so good stuff.
