### ISSUE TITLE
`cannot load such file -- benchmark/ips/noop_suite`

### ISSUE THREAD

**Issue by ioquatix** [evanphx/benchmark-ips#116]
~~~
Failure/Error: require 'benchmark/ips'

LoadError:
  cannot load such file -- benchmark/ips/noop_suite
# /Users/samuel/.gem/ruby/3.0.0/gems/benchmark-ips-2.9.0/lib/benchmark/ips.rb:8:in `require'
# /Users/samuel/.gem/ruby/3.0.0/gems/benchmark-ips-2.9.0/lib/benchmark/ips.rb:8:in `<top (required)>'
# ./spec/db/benchmark_spec.rb:23:in `require'
# ./spec/db/benchmark_spec.rb:23:in `<top (required)>'
~~~

I'm not sure what's going on, but the latest release seems broken.

I'd suggest you change to use `require_relative` everywhere too: https://github.com/evanphx/benchmark-ips/blob/dea7eb1df656f40c2455a4d69ede8601ba82bf5f/lib/benchmark/ips.rb#L8

~~~
gem "benchmark-ips", "~> 2.8.0"
~~~

fixes the issue for me.

**Comment by okeeblow** [comment]
https://github.com/evanphx/benchmark-ips/pull/115

**Comment by evanphx** [comment]
2.9.1 is out with the fix, sorry about that!

**Comment by ioquatix** [comment]
Thanks!
