### ISSUE TITLE
Fork support?

### ISSUE THREAD

**Issue by mperham** [evanphx/benchmark-ips#138]
Hello!

I'm trying to benchmark a few different approaches to a problem but the various approaches make process-global changes which can pollute and affect the runtimes of the other reports. What do you think about:

1. Running each report in its own child fork?
2. Adding support for a post-fork, pre-report callback to trigger the global state change?

Specifically the `flavor!` call below makes global changes to ::JSON, which can affect everything.

```ruby
Benchmark.ips do |x|
  x.report("Sidekiq::Job v7") do |times|
    i = 0
    while i < times
      MyJob.perform_async("foo", 123, {"mike" => true}, Time.now.to_f)
      i += 1
    end
  end
  x.report("ActiveJob v#{ActiveJob.version}") do |times|
    i = 0
    while i < times
      AJob.perform_later(:foo, 123, {mike: 0..5}, Time.now)
      i += 1
    end
  end
  x.report("Sidekiq::Job v8") do |times|
    Sidekiq::JSON.flavor!(:v8)
    i = 0
    while i < times
      MyJob.perform_async(:foo, 123, {"mike" => 0..5}, Time.now)
      i += 1
    end
  end
end
```

**Comment by eregon** [comment]
I think that can already be achieved by using `hold!`: https://github.com/evanphx/benchmark-ips?tab=readme-ov-file#independent-benchmarking
That's also more general because fork only works on CRuby and non-Windows.

**Comment by mperham** [comment]
Ah, ok. I didn't understand that section when I read it.

**Comment by pboling** [comment]
I've added the ability to re-namespace a gem so it can be benchmarked alongside a different version of itself, in `gem_bench` v2.0.3, out now.

See: https://github.com/pboling/gem_bench
Real usage example here: https://github.com/panorama-ed/memo_wise/pull/339
