### ISSUE TITLE
Gemspec is missing

### ISSUE THREAD

**Issue by kirs** [evanphx/benchmark-ips#23]
Due the missing gemspec, the gem can't be used with Bundler as a git repo:

```
gem 'benchmark-ips', github: 'evanphx/benchmark-ips', commit: 'abc'
```

@evanphx do you mind if I send a PR fixing it?

**Comment by evanphx** [comment]
There is really no reason to use benchmark-ips from git directly. Why not use the gem?

**Comment by kirs** [comment]
Actually there is. I make a fix (https://github.com/kirs/benchmark-ips/compare/quiet-mode) and was going to use it directly from the branch on GIthub.

**Comment by evanphx** [comment]
Ah! That's make mistake, I should release that.

**Comment by evanphx** [comment]
Er, that's on your repo. Well, you can always make a gemspec in your fork. :smile_cat:

**Comment by kirs** [comment]
Thanks a lot! Do you think I can send a PR with :quiet option?

**Comment by evanphx** [comment]
Sure! Send away!
