### ISSUE TITLE
[feature request] JSON output

### ISSUE THREAD

**Issue by ryanmjacobs** [evanphx/benchmark-ips#28]
Right now I'm using awk, sed, etc. to parse i/ps and std. dev from the output. It would be nice to have some JSON output function.

Something like this would be nice:
```json
[
  {
    "name": "fn. 1",
    "i/ps": 12.34,
    "perc. std. dev.": 56,
    "etc.": "etc."
  }
]
```

Maybe, I'll try to throw something together later.

**Comment by evanphx** [comment]
Done by #29
