### ISSUE TITLE
Travis CI Build unknown

### ISSUE THREAD

**Issue by JuanitoFatas** [evanphx/benchmark-ips#30]
The travis page of benchmark-ips is here: https://travis-ci.org/evanphx/benchmark-ips

[![Build Status](https://travis-ci.org/evanphx/benchmark-ips.svg)](https://travis-ci.org/evanphx/benchmark-ips)

What do we need to do to activate it on Travis CI :smile: ? Thanks!!!

**Comment by evanphx** [comment]
It's enabled now!
