### ISSUE TITLE
New release timelime

### ISSUE THREAD

**Issue by splattael** [evanphx/benchmark-ips#39]
Hi Evan,

the latest release of `benchmark-ips` has been mid January.
Since then some nice changes have been made: https://github.com/evanphx/benchmark-ips/compare/75d789b...master

Do you plan to release a new version soonish?

Kind regards,
  Peter

**Comment by evanphx** [comment]
Sorry for the delay! Released now.

**Comment by splattael** [comment]
Awesome, thank you :) :green_heart:
