### ISSUE TITLE
rdoc?

### ISSUE THREAD

**Issue by zenspider** [evanphx/benchmark-ips#71]
The `ri` info available on `Benchmark::IPS`, `Benchmark.ips`, and `Benchmark::IPS.ips` is either nonexistant or devoid of information to the point where it isn't useful at all. Please for the love of god make the doco on this project useful. I don't want to have to google this stuff just because I only use it once a month.

**Comment by evanphx** [comment]
Sorry to take so long to get back to this. There is some rdoc on all of those, could you give me some feedback on what you're looking for so I can make it better? Here is the docs for `ips`: https://github.com/evanphx/benchmark-ips/blob/master/lib/benchmark/ips.rb#L23-L27

**Comment by zenspider** [comment]
```
9999 % ri Benchmark.ips
Nothing known about Benchmark.ips
```

None there, which is the thing that people are going to look up the most.

```
10000 % ri Benchmark::IPS
= Benchmark::IPS

(from gem benchmark-ips-2.7.2)
------------------------------------------------------------------------------
Benchmark in iterations per second, no more guessing! @see
https://github.com/evanphx/benchmark-ips



[why are all these blank lines here?]



------------------------------------------------------------------------------
= Constants:

CODENAME:
  CODENAME of current version.

VERSION:
  Benchmark-ips Gem version.


= Class methods:

  options

= Instance methods:

  ips
```

Honestly, as a user I shouldn't even know that it is Benchmark::IPS, so I'm not sure why I even included it in the example other than through code reading. Maybe it could also be a logical guess based on the gem name?

In either case, this rdoc provides nothing to go off of, and documents things that don't help (eg Add `# :nodoc:` to `CODENAME` and `VERSION`).

This is the class-level doc. An example or template at the very least would be useful here (tho I still think Benchmark::IPS is an unintuitive vector for most users).

```
10001 % ri Benchmark::IPS.ips
= Benchmark::IPS.ips

(from gem benchmark-ips-2.7.2)
=== Implementation from IPS
------------------------------------------------------------------------------
  ips(*args) { |job| ... }

------------------------------------------------------------------------------

Measure code in block, each code's benchmarked result will display in
iteration per second with standard deviation in given time. @param time
[Integer] Specify how long should benchmark your code in seconds. @param
warmup [Integer] Specify how long should Warmup time run in seconds. @return
[Report]
```

The actual meat of the gem, but this doco doesn't do anything to help a newb get up and running. It at least needs to mention `x.report` and `x.compare!` or at least where to go to look up where things are actually taking place.

**Comment by zenspider** [comment]
anything? This keeps biting me over and over.

**Comment by zenspider** [comment]
dude...

**Comment by evanphx** [comment]
Closing this as #83 hopefully dealt with it.

**Comment by zenspider** [comment]
```
9986 % ri Benchmark::IPS
= Benchmark::IPS

(from gem benchmark-ips-2.13.0)
------------------------------------------------------------------------
Benchmark in iterations per second, no more guessing! @see
https://github.com/evanphx/benchmark-ips









------------------------------------------------------------------------
= Constants:

CODENAME:
  CODENAME of current version.

VERSION:
  Benchmark-ips Gem version.


= Class methods:

  options

= Instance methods:

  ips
```

it didn't

**Comment by evanphx** [comment]
Sorry for not looking at this for so long. The docs are currently under `Benchmark.ips`, i'll add a note in the top about that.
