### ISSUE TITLE
API change without deprecation in `Benchmark::IPS::Report`

### ISSUE THREAD

**Issue by tgxworld** [evanphx/benchmark-ips#76]
I noticed that doing something like this no longer works on the latest version of this gem.

```
report = Benchmark.ips(time, warmup, true) do |bm|
  bm.report(label, &block)
end

entry = report.entries.first

puts entry.ips
puts entry.stddev_percentage
```
It looks like the accessor/method have been removed in https://github.com/evanphx/benchmark-ips/pull/69 but the changes were not reflected in https://github.com/evanphx/benchmark-ips/commit/a512373de592243e798566349a9d1ec8ae274847. 

I'll like to find out if `Benchmark::IPS::Report` is meant for the Gem's internal use or if they are exposed as public APIs. I'll be more than happy to submit a PR to deprecate the methods first instead if the latter is true.

**Comment by evanphx** [comment]
I'm quite sorry about that. It was a mistake to break those APIs because I had not indicated if they were public or not.

These accessors should be added back in.

**Comment by tgxworld** [comment]
@evanphx No worries :) Thank you for fixing it. I really appreciate it :)
