### ISSUE TITLE
SHARE=1 not working: HTTP Response with status 400 (Bad Request)

### ISSUE THREAD

**Issue by etagwerker** [evanphx/benchmark-ips#82]
Hello, 

First of all, thank you for such a useful gem! 

I just tried to use SHARE=1 to upload my results to https://benchmark.fyi but I got this error message: 

```
$ SHARE=1 bundle exec ruby benchmarks/unless_nil_vs_if_object.rb
Warming up --------------------------------------
          unless nil    63.507k i/100ms
           if object   271.532k i/100ms
Calculating -------------------------------------
          unless nil    799.058k (± 3.0%) i/s -      4.001M in   5.011766s
           if object     12.172M (± 5.2%) i/s -     60.823M in   5.011318s

Comparison:
           if object: 12172119.9 i/s
          unless nil:   799058.5 i/s - 15.23x  slower

Error sharing report
```

After debugging `benchmark-ips`, I noticed that I'm getting this response: 

```
[12] pry(#<Benchmark::IPS::Share>)> res
=> #<Net::HTTPBadRequest 400 Bad Request readbody=true>
```

It's weird, because my code is pretty standard: 

```ruby
require 'benchmark/ips'

Benchmark.ips do |x|
  OBJECT = "nil".freeze

  x.report("unless nil") do
    20.times do
      true unless OBJECT.nil?
    end
  end

  x.report("if object") do
    true if OBJECT
  end

  x.compare!
end
```

This is the body in the request: 

```
[8] pry(#<Benchmark::IPS::Share>)> req.body
=> "{\"entries\":[{\"name\":\"unless nil\",\"central_tendency\":797392.5723155453,\"ips\":797392.5723155453,\"error\":34976,\"stddev\":34976,\"microseconds\":5076026.0,\"iterations\":4038208,\"cycles\":63097},{\"name\":\"if object\",\"central_tendency\":12144478.462478887,\"ips\":12144478.462478887,\"error\":644754,\"stddev\":644754,\"microseconds\":5012625.0,\"iterations\":60690718,\"cycles\":268543}],\"options\":{\"compare\":true}}"
```

After reviewing the code for `benchmark.fyi`, it seems that the problem is with some of the parameters: https://github.com/evanphx/benchmark.fyi/blob/master/app/controllers/reports_controller.rb#L8-L54

If any of the keys for the entry is not recognized, it will error out with a 400 response code: https://github.com/evanphx/benchmark.fyi/blob/master/app/controllers/reports_controller.rb#L6

So, it seems to be an issue with `benchmark.fyi`, not `benchmark-ips`:

The API accepts these keys per entry:

```
DATA_KEY = %W!name ips stddev microseconds iterations cycles!
```

But `benchmark-ips` is sending these keys: 

```
["name", "central_tendency", "ips", "error", "stddev", "microseconds", "iterations", "cycles"]
```

What do you think is the best solution to solve this in `benchmark.fyi`?

**Comment by evanphx** [comment]
Fixed benchmark.fyi with your patch, so we're all good!
