### ISSUE TITLE
Calculation is stuck

### ISSUE THREAD

**Issue by prettyGoo** [evanphx/benchmark-ips#87]
When I try to benchmark some code, my program seems to be stuck at calculation phase after successful warm-up

I tried next piece of code (with and without manually set time and warmup):
```ruby
require "benchmark/ips"

a = (1..10).to_a
b = (1..10).to_a

Benchmark.ips do |x|
  x.config(:time => 2, :warmup => 2)
  x.report("+ code performance") { a + b }
  x.report("concat code performance") {  a.concat(b) }
  x.compare!
end
```

**ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]** and **benchmark 2.7.2** were used

**Comment by evanphx** [comment]
The reason is your code is getting slower and slower with each iteration
because you’re growing a on every interaction. The work in the block needs
to do the same work each time and you’re forcing it to allocate and copy
huge amounts of memory on each iteration.
