### ISSUE TITLE
Add factor to control times parameter

### ISSUE THREAD

**Issue by ioquatix** [evanphx/benchmark-ips#94]
https://github.com/evanphx/benchmark-ips/blob/0bb23ea1f5d8f65416629505889f6dfc550fa4a6/lib/benchmark/ips/job.rb#L256

Do you think it's possible to add a offset and/or factor to control the times parameter?

It would be nice if we could tell it to run at least 10 iterations minimum, for example.

**Comment by eregon** [comment]
I think this is fixed by https://github.com/evanphx/benchmark-ips/pull/96
