### ISSUE TITLE
Release new gem version

### ISSUE THREAD

**Issue by jcoleman** [evanphx/benchmark-ips#97]
The current released version is 2.7.2 from almost four years ago. However new features (`#save!`, for example, 18 months ago) have come in since then.

Would you be able to push a new version to RubyGems?

**Comment by junaruga** [comment]
https://rubygems.org/gems/benchmark-ips
It seems the 2.8.0 was released today.

**Comment by junaruga** [comment]
But I failed to install it on my environment.
You can see https://github.com/evanphx/benchmark-ips/issues/100 .
